// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC-YwN1rgjJfVkMYK_s5cvFbDt_hStWWY',
    appId: '1:331639788063:web:d23958eb15c740346ffb2a',
    messagingSenderId: '331639788063',
    projectId: 'dotby-37e3f',
    authDomain: 'dotby-37e3f.firebaseapp.com',
    storageBucket: 'dotby-37e3f.firebasestorage.app',
    measurementId: 'G-87E5JFBTR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ3t6u86MbCruEt_Dx2IrXia955_0QSN4',
    appId: '1:331639788063:android:934d846614844e6f6ffb2a',
    messagingSenderId: '331639788063',
    projectId: 'dotby-37e3f',
    storageBucket: 'dotby-37e3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ZyhPrwdT6wbILPFGYycQSIrqdQpirXA',
    appId: '1:331639788063:ios:dc8bcb10b5179ebc6ffb2a',
    messagingSenderId: '331639788063',
    projectId: 'dotby-37e3f',
    storageBucket: 'dotby-37e3f.firebasestorage.app',
    iosBundleId: 'com.example.dotby1',
  );
}
